spring:
  profiles.active: test
jasypt:
  profiles.active: test
  
---

spring:
  profiles: development
  datasource:
    db-master:
      url: jdbc:sqlserver://10.88.89.201;databaseName=dm_Base_Repo_docbase
      username: sa
      password: 2qVUNy//PHDCmtSdZVq6TqOFgijXNMdF
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    db-temp:
      url: jdbc:sqlserver://10.88.89.201;databaseName=DocReqDB
      username: sa
      password: 2qVUNy//PHDCmtSdZVq6TqOFgijXNMdF
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:      
    databasePlatform: org.hibernate.dialect.SQLServerDialect
    database: SQL_SERVER
    openInView: false
    showSql: true
    generateDdl: false
    
share-folder:
  profiles: development
  domain: 10.88.89.203
  name: file
  user: Administrator
  pass: 2qVUNy//PHDCmtSdZVq6TqOFgijXNMdF

---

spring:
  profiles: test
  datasource:
    db-master:
      url: jdbc:sqlserver://10.88.88.141;databaseName=dm_Base_Repo_docbase
      username: sa
      password: 2qVUNy//PHDCmtSdZVq6TqOFgijXNMdF
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    db-temp:
      url: jdbc:sqlserver://10.88.88.141;databaseName=DocReqDB
      username: sa
      password: 2qVUNy//PHDCmtSdZVq6TqOFgijXNMdF
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:      
    databasePlatform: org.hibernate.dialect.SQLServerDialect
    database: SQL_SERVER
    openInView: false
    showSql: true
    generateDdl: false

jasypt:
  profiles: test
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: test
    
share-folder:
  profiles: test
  domain: 10.88.88.141
  name: dms_req_upload
  user: Administrator
  pass: adnz3Ffhx5I9z3otbh+toDqHUM0E7/Ny
  
scheduler:
  cronExpression: 1 * * * * *
